### ISSUE TITLE
'process had died' problem

### ISSUE THREAD

**Issue by ehdwp** [YukunXia/VLOAM-CMU-16833#11]
Hi.

I am having a problem when I try step4 in this page
https://github.com/YukunXia/VLOAM-CMU-16833/tree/master/src/vloam_main#usage-1

I follow this page and use roptopic pub.
But, my roslaunch terminal showed error "[vloam_main_node-1] process has died [pid 4477, exit code -11, .."

I am not sure whether I am missing something here.
Any help is much appreciated.

**Comment by YukunXia** [comment]
Just to double-check, by trying step 4, you wanna repeat step 3 without quitting the roslaunch. If yes, I couldn't remember any error like this. And it's usually very hard to debug similar ROS issues. Could you try setting breakpoints and see which line of code killed the vloam_main_node?

**Comment by ehdwp** [comment]
I'm sorry. I wrote wrong step.  I have a problem at step 3.
![Screenshot from 2022-02-14 15-59-14](https://user-images.githubusercontent.com/94116369/153815724-44e7a0fb-27b9-4aa4-ab47-dcac2946ab5c.png)

in screenshot, I did 'roslaunch vloam_main vloam_main.launch' in first terminal and 'rostopic pub /load_small_dataset_action_server/goal ..' in another terminal.

And my roslaunch terminal showed error 'process has died'. 

thank you

**Comment by YukunXia** [comment]
Ok. As I said, it's very hard to directly identify the problem source from `process had died`. I'd recommend taking a closer look at the following function and maybe printing a marker message after each line. 

https://github.com/YukunXia/VLOAM-CMU-16833/blob/59f37f888356d723f7ff7756e832f9ec3d35adf5/src/vloam_main/src/vloam_main_node.cpp#L125-L180

I suspect the problem might come from the environment setup, especially a dependency issue, because I've run the code plenty of times, and no other people reported similar issues.

**Comment by ehdwp** [comment]
OK. Thank you for your reply
