### ISSUE TITLE
Another Dataset

### ISSUE THREAD

**Issue by parthmalpathak** [YukunXia/VLOAM-CMU-16833#13]
Hello Yukun,
Have you attempted to use any other dataset for your implementation? If so, any suggestions for that?

**Comment by YukunXia** [comment]
Not yet, but I'd imagine that, in a new dataset, you can try renaming the subscribed topics for the 3d point clouds, images, and ego-robot transformations

**Comment by arashizn** [comment]
Hello YuKun, if I want to build a map in real time using the data my lidar and camera collected, what should I do?

**Comment by YukunXia** [comment]
> Hello YuKun, if I want to build a map in real time using the data my lidar and camera collected, what should I do?

Hi @arashizn , as my [previous comment](https://github.com/YukunXia/VLOAM-CMU-16833/issues/13#issuecomment-1117988508) suggested in this thread, you could try replacing or remapping your lidar and camera topics to the ones in this repository. 

Besides, to be honest, this repository was created mainly to fulfill a course project requirement, and we didn't continue developing and refining it. The repo remains as a prototype working with the KITTI dataset, rather than a ready-to-go product applicable to a real robot.

**Comment by arashizn** [comment]
> 

Really thanks, just like you, I'm designing my course project, i want to integrate the code to achieve slam using my lidar and camera. I'll try!
