### ISSUE TITLE
Error in cv

### ISSUE THREAD

**Issue by didzdissanayaka8** [YukunXia/VLOAM-CMU-16833#7]
I have OpenCV 4.5.3 but I am getting the following errors when I tried to build the package. Is it because SIFT is no longer available in OpenCV? (for the second error)  

/home/didula/BVLOAM_ws/src/visual_odometry/src/image_util.cpp: In member function ‘std::vector<cv::KeyPoint> vloam::ImageUtil::detKeypoints(cv::Mat&)’:
/home/didula/BVLOAM_ws/src/visual_odometry/src/image_util.cpp:56:7: error: ‘ScoreType’ is not a member of ‘cv::ORB’
       cv::ORB::ScoreType scoreType = cv::ORB::FAST_SCORE;
       ^
/home/didula/BVLOAM_ws/src/visual_odometry/src/image_util.cpp:59:104: error: ‘scoreType’ was not declared in this scope
       detector = cv::ORB::create(num_features, scaleFactor, nlevels, edgeThreshold, firstLevel, WTA_K, scoreType,
                                                                                                        ^
/home/didula/BVLOAM_ws/src/visual_odometry/src/image_util.cpp:65:22: error: ‘cv::SIFT’ has not been declared
       detector = cv::SIFT::create();
                      ^
/home/didula/BVLOAM_ws/src/visual_odometry/src/image_util.cpp: In member function ‘cv::Mat vloam::ImageUtil::descKeypoints(std::vector<cv::KeyPoint>&, cv::Mat&)’:
/home/didula/BVLOAM_ws/src/visual_odometry/src/image_util.cpp:192:21: error: ‘cv::SIFT’ has not been declared
     extractor = cv::SIFT::create();
                     ^
visual_odometry/CMakeFiles/image_util.dir/build.make:62: recipe for target 'visual_odometry/CMakeFiles/image_util.dir/src/image_util.cpp.o' failed
make[2]: *** [visual_odometry/CMakeFiles/image_util.dir/src/image_util.cpp.o] Error 1
CMakeFiles/Makefile2:2626: recipe for target 'visual_odometry/CMakeFiles/image_util.dir/all' failed
make[1]: *** [visual_odometry/CMakeFiles/image_util.dir/all] Error 2

**Comment by YukunXia** [comment]
Yes, I've seen some similar errors. 

There's a temporary solution. Just comment out the SIFT-related lines. By default, the program, if I remember correctly, uses the Shi-Tomasi detector and ORB descriptor. 

To understand the error, SIFT was moved from OpenCV's contrib repo to the main repo, because SIFT's patent protection has expired. So some SIFT code may deprecate and cause errors. My code is based on this new change, which should be fine if you haven't installed the contrib one. However, the system's OpenCV, installed by apt-get, may interfere, and claim that you need to use the SIFT in contrib. That OpenCV seems not able to be uninstalled, since ROS relies on that. So as you can see, my OpenCV's inclusions are all `#include <opencv4/opencv2/xxxx.hpp>` to force using the latest manually installed verion. I hate that OpenCV requires these complex settings, and you may install the latest OpenCV in a different way, so that inclusion trick didn't help you.

If you really wanna dig into this error. A suggestion is to take a look at this StackOverflow Post: https://stackoverflow.com/a/65586705/9556578, and check where's the true included OpenCV. If it's the correct one, double check if there's a SIFT function under the `cv ` namespace.

Good luck!

**Comment by didzdissanayaka8** [comment]
Hi,

Thank you very much for your reply. I installed OpenCV 4.5.3 by cloning the OpenCV GitHub repo for main and contrib. When I cmake I made sure to enable non-free packages as well. Anyway I think I should be okay with the second error when I comment the SIFT related code. 

I was not that clear whether I can comment the cv::ORB::FAST_SCORE part as well. Do you use the FAST feature detector in the actual implementation?

**Comment by YukunXia** [comment]
By default, FAST is not used. Feel free to comment it out too : )

**Comment by leslieburke** [comment]
@didzdissanayaka8 I got the same problem, did u solve it?

**Comment by opendipius849-lab** [comment]
Mai bot has no privacy tag
