### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by dilaxy123** [YukunXia/VLOAM-CMU-16833#8]
Hi, I have OpenCV 4.5.1 installed and when I catkin_make I get the following error. May I know what ubuntu version you used for the original version? 

make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libconsole_bridge.soopencv_ml', needed by '/home/dilaxy/BVLOAM_ws/devel/lib/libimage_util.so'.  Stop.
CMakeFiles/Makefile2:2626: recipe for target 'visual_odometry/CMakeFiles/image_util.dir/all' failed
make[1]: *** [visual_odometry/CMakeFiles/image_util.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Built target vloam_tf
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libconsole_bridge.soopencv_ml', needed by '/home/dilaxy/BVLOAM_ws/devel/lib/libpoint_cloud_util.so'.  Stop.
CMakeFiles/Makefile2:2702: recipe for target 'visual_odometry/CMakeFiles/point_cloud_util.dir/all' failed
make[1]: *** [visual_odometry/CMakeFiles/point_cloud_util.dir/all] Error 2

**Comment by YukunXia** [comment]
My system is Ubuntu 20.04, but I think the problem is that you don't have `libconsole_bridge.so` and `opencv_ml`. Maybe you can google how to install them. I briefly looked at those searching results, and the first seems related to ROS. Also, why `libconsole_bridge.so` and `opencv_ml` are connected seamlessly? That really looks weird.

**Comment by dilaxy123** [comment]
I had to manually add the OpenCV directory in cmake file which fixed the issue. I think it is just a problem with my system. Thank you very much for your help
